# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34bb7e414334470fdeb83bce7e3a1e09a4bc40a9b0d2fa2e2cf8ab78a04a3233c557f106c13e6864f2b722548bb9ffd14a406dd4af5e4f5f2148132dd914cf9b

test:
  secret_key_base: 7aa53222abc7d7692abd9ade907d85d121a22b8a332c7bf635bfc589e55ab86ac45b115bfa7e1cbfa5398850b13832257ea7516169c74324ca037234cda1e579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
